spring:
  flyway:
    baseline-on-migrate: true
    check-location: false
  main:
    banner-mode: off
  profiles.active: 'local'
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0KB
      max-file-size: 2MB
      max-request-size: 200MB
appconfiguration.encrypt: 'aaa'

