appconfiguration:
  accessBefore: 1
  deleteAfter: 7
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource.url: 'jdbc:h2:file:C:\\Users\\user\\Desktop\\Inzynierka\\documents\\db'
  jpa:
    hibernate:
      ddl-auto: create-drop
