appconfiguration:
  accessBefore: 1
  deleteAfter: 7
spring:
  flyway:
    baseline-on-migrate: true
    check-location: false
  h2.console:
    enabled: true
    path: '/console'
  datasource.url: 'jdbc:h2:file:C:\\Users\\user\\Desktop\\Inzynierka\\documents\\db'
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
